TraceCondition:
  LogsDir: ./tracer_logs
  Targets:
  - Func: price_out_impl
    Recursive: false
    TriggerFunc: price_out_impl
    Triggers:
      - arg0.feasible == 1836017711
      # - arg0.nodes.orientation == 1
      # - auto arg0 arg2
  # - Func: update_tree
  #   Recursive: false
  #   TriggerFunc: update_tree
  #   Triggers:
  #     - arg0 == 10 && arg1 < 20
      # - arg5.orientation = 2 || arg5.child.orientation = 3
      # - auto arg0 arg1
  - Func: write_objective_value
    Recursive: false
    TriggerFunc: write_objective_value
    Triggers:
      - outfile == mcf.out
